### ISSUE TITLE
Normalize stage types and assign a colour to each

### ISSUE THREAD

**Issue by JanMaxime** [com-480-data-visualization/datavis-project-2022-datawiz#20]
Across editions, names of stage types have changed (Plain stage, Flat stage, Stage with mountain, Stage with mountain(s))

Ideally, we should normalize so that we only have a few stage type. This can be modified in tdf_stages.csvS

Also, we need to assign a colour to each of them (this can be done at the bottom of "map_utils.js")

**Comment by jonaskon** [comment]
I suggest that we use the stage types I describe in the information tab (see https://github.com/com-480-data-visualization/datavis-project-2022-datawiz/pull/22 if not yet merged).

They are the most important ones I believe.
